### ISSUE TITLE
Ownership of this repo

### ISSUE THREAD

**Issue by mikael-lindstrom** [evenstensberg/require-id-hash#2]
Hi @evenstensberg,  we do not seem to use this repo in Telia anymore and have no one that can maintain it, do you want me to transfer it to you or should we close it down?

**Comment by evenstensberg** [comment]
Send it my way! :)

**Comment by mikael-lindstrom** [comment]
Great! Unfortunately it seems that I'm only able to transfer to myself or another organisation... but you are admin of this repo so you should be able to transfer this repo to yourself!

**Comment by mikael-lindstrom** [comment]
Thanks for your help 👍 closing this issue!

**Comment by evenstensberg** [comment]
Same goes for you, was nice working alongside you at Telia, wish you all the best & hope you're having a great summer!
